-- Bank Connector Framework: two brand-new models, since bank connectors
-- are a distinct concept from Connection (that's Better Auth-adjacent
-- OAuth data-source connections for Gmail/Outlook/Yahoo; bank connectors
-- are separate demo/plugin registrations, no OAuth flow, no existing
-- Connection row). Purely additive — no existing table touched.
--
-- Hand-written and reviewed before applying (not generated by
-- `prisma migrate dev`'s auto-diff), same as the sync_job_provider_fields
-- migration.

-- CreateEnum
CREATE TYPE "BankConnectionStatus" AS ENUM ('CONNECTED', 'DISCONNECTED', 'AUTHENTICATING', 'REAUTHENTICATION_REQUIRED', 'ERROR');

-- CreateEnum
CREATE TYPE "BankAccountType" AS ENUM ('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'LOAN', 'INVESTMENT', 'WALLET', 'BUSINESS', 'CASH');

-- CreateEnum
CREATE TYPE "BankAccountStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'CLOSED', 'ERROR');

-- CreateTable
CREATE TABLE "bank_connector_states" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "connectorId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "lastHealth" JSONB,
    "lastConnection" "BankConnectionStatus",
    "lastSyncAt" TIMESTAMP(3),
    "installedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bank_connector_states_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bank_accounts" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "connectorId" TEXT NOT NULL,
    "institution" TEXT NOT NULL,
    "accountName" TEXT NOT NULL,
    "accountType" "BankAccountType" NOT NULL,
    "maskedNumber" TEXT NOT NULL,
    "currency" TEXT NOT NULL,
    "balance" DECIMAL(14,2) NOT NULL,
    "availableBalance" DECIMAL(14,2) NOT NULL,
    "lastSynced" TIMESTAMP(3),
    "status" "BankAccountStatus" NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bank_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "bank_connector_states_organizationId_connectorId_key" ON "bank_connector_states"("organizationId", "connectorId");

-- CreateIndex
CREATE INDEX "bank_accounts_organizationId_connectorId_idx" ON "bank_accounts"("organizationId", "connectorId");

-- AddForeignKey
ALTER TABLE "bank_connector_states" ADD CONSTRAINT "bank_connector_states_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bank_accounts" ADD CONSTRAINT "bank_accounts_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
