"use server";

import { generateText } from "@/lib/ai/provider";
import type { Insights } from "@/lib/insights/engine";
import type { TimelineGroup } from "@/lib/timeline/engine";
import type { BudgetStatus } from "@/types/budget";
import type { FinancialEvent } from "@/types/event";
import type { ExplanationCoachSummary } from "@/types/explanation";
import type { ForecastCoachSummary } from "@/types/forecast";
import type { QueryContext, QueryIntent } from "@/types/query";
import type { RecurringCoachSummary } from "@/types/recurring";
import type { Recommendation } from "@/types/recommendation";
import type { Transaction } from "@/types/transaction";

export interface MemoryStats {
  totalEntries: number;
}

export interface ReviewStats {
  totalTransactions: number;
  reviewedCount: number;
  pendingCount: number;
}

/** Structured merchant knowledge, not a raw name/alias — the Coach reasons
 * about "Amazon, E-Commerce, ₹12,000 across 5 visits" rather than parsing
 * free-form transaction notes itself. */
export interface MerchantCoachSummary {
  canonicalName: string;
  industry: string;
  category: string;
  tags: string[];
  isRecurringFriendly: boolean;
  transactionCount: number;
  totalSpend: number;
  averageTransactionAmount: number;
}

export interface CoachInput {
  insights: Insights;
  timeline: TimelineGroup[];
  /** Last 10 transactions, newest first. */
  recentTransactions: Transaction[];
  /** Merchant Knowledge Graph profiles — the Coach consumes these instead
   * of raw merchant names or aliases. */
  merchantSummaries: MerchantCoachSummary[];
  memoryStats: MemoryStats;
  reviewStats: ReviewStats;
  /** Already-computed by the Budget Engine — the LLM must not recalculate these. */
  budgetStatuses: BudgetStatus[];
  /** Already-detected by the Events Engine — the LLM must not discover these itself. */
  events: FinancialEvent[];
  /** Already-generated by the Decision Engine — the LLM must not invent new ones. */
  recommendations: Recommendation[];
  /** Already-detected by the Recurring Transaction Intelligence Engine —
   * the LLM must not try to spot recurring behavior itself. */
  recurringSummaries: RecurringCoachSummary[];
  /** Already-computed by the Cash Flow Forecast Engine — the LLM explains
   * this, it never calculates a projection itself. */
  forecastSummary: ForecastCoachSummary | null;
  /** Already-generated by the Financial Insight & Explanation Engine —
   * each one's `reason` and `supportingEvidence` are the authoritative
   * explanation for its object. The LLM narrates these, it never derives
   * its own reasoning from the raw analytics below. */
  explanations: ExplanationCoachSummary[];
}

export interface CoachOutput {
  summary: string;
  goodHabits: string[];
  watchOutFor: string[];
  suggestions: string[];
}

function effectiveCategory(transaction: Transaction): string {
  return transaction.userCategory ?? transaction.aiCategory ?? "Other";
}

function buildAnalyticsPayload(input: CoachInput) {
  return {
    totalSpent: input.insights.totalSpent,
    transactionCount: input.insights.totalTransactions,
    categoryBreakdown: input.insights.categoryBreakdown.map((entry) => ({
      category: entry.category,
      total: entry.total,
      percentage: Math.round(entry.percentage * 10) / 10,
    })),
    timelineSummary: input.timeline.map((group) => ({
      period: group.label,
      totalAmount: group.totalAmount,
      transactionCount: group.transactionCount,
    })),
    largestExpense: input.insights.largestExpense,
    mostUsedCategory: input.insights.topCategory,
    mostUsedPaymentMethod: input.insights.topPaymentMethod,
    averageExpense: input.insights.averageExpense,
    recentTransactions: input.recentTransactions.slice(0, 10).map((t) => ({
      amount: t.amount,
      category: effectiveCategory(t),
      paymentMethod: t.paymentMethod,
      date: t.date,
    })),
    merchants: input.merchantSummaries.map((m) => ({
      name: m.canonicalName,
      industry: m.industry,
      category: m.category,
      tags: m.tags,
      isRecurringFriendly: m.isRecurringFriendly,
      transactionCount: m.transactionCount,
      totalSpend: m.totalSpend,
      averageTransactionAmount: Math.round(m.averageTransactionAmount),
    })),
    memoryLayer: {
      rememberedMappingCount: input.memoryStats.totalEntries,
    },
    review: {
      totalTransactions: input.reviewStats.totalTransactions,
      reviewedCount: input.reviewStats.reviewedCount,
      pendingCount: input.reviewStats.pendingCount,
    },
    budgets: input.budgetStatuses.map((b) => ({
      category: b.category,
      monthlyLimit: b.monthlyLimit,
      currentSpend: b.currentSpend,
      remainingAmount: b.remainingAmount,
      percentageUsed: Math.round(b.percentageUsed * 10) / 10,
      transactionCount: b.transactionCount,
      daysRemainingThisMonth: b.daysRemainingThisMonth,
      status: b.status,
    })),
    events: input.events.map((e) => ({
      type: e.type,
      title: e.title,
      description: e.description,
      date: e.date,
      severity: e.severity,
    })),
    recommendations: input.recommendations.map((r) => ({
      title: r.title,
      description: r.description,
      category: r.category,
      priority: r.priority,
      reason: r.reason,
      action: r.action,
    })),
    recurring: input.recurringSummaries.map((r) => ({
      title: r.title,
      frequency: r.frequency,
      averageAmount: Math.round(r.averageAmount),
      nextExpectedOccurrence: r.nextExpectedOccurrence,
      status: r.status,
      isSubscription: r.isSubscription,
      isIncome: r.isIncome,
    })),
    forecast: input.forecastSummary && {
      projectedEndOfMonthBalance: Math.round(input.forecastSummary.projectedEndOfMonthBalance),
      expectedIncome: Math.round(input.forecastSummary.expectedIncome),
      expectedExpenses: Math.round(input.forecastSummary.expectedExpenses),
      expectedSavings: Math.round(input.forecastSummary.expectedSavings),
      dailySafeSpend: Math.round(input.forecastSummary.dailySafeSpend),
      confidence: Math.round(input.forecastSummary.confidence * 100) / 100,
      daysRemaining: input.forecastSummary.daysRemaining,
      categoryRisks: input.forecastSummary.categoryRisks.map((c) => ({
        category: c.category,
        riskLevel: c.riskLevel,
        projectedPercentageUsed:
          c.projectedPercentageUsed === null ? null : Math.round(c.projectedPercentageUsed),
      })),
    },
    explanations: input.explanations.map((e) => ({
      objectType: e.objectType,
      title: e.title,
      reason: e.reason,
      supportingEvidence: e.supportingEvidence,
      confidence: Math.round(e.confidence * 100) / 100,
    })),
  };
}

function buildPrompt(analytics: ReturnType<typeof buildAnalyticsPayload>): string {
  return [
    "You are a financial coach analyzing a user's already-categorized spending data.",
    "Do not classify or re-categorize transactions — categorization is already finalized upstream.",
    "The `budgets` field, if present, was computed by a deterministic budget engine — treat currentSpend, remainingAmount, percentageUsed, and status as already-correct facts. Do not recalculate, second-guess, or restate them as approximations; only explain what they mean and what to do about them.",
    "The `events` field lists financial events already detected by a deterministic events engine (large expenses, recurring expenses, budget alerts, new merchants, spending spikes, etc.). Do not try to discover additional events yourself or contradict the ones listed — only explain what they mean for the user and what, if anything, to do about them.",
    "The `recommendations` field lists actionable recommendations already generated by a deterministic decision engine, each with its own reason and suggested action. Do not invent new recommendations or contradict these — your `suggestions` output should draw from and explain these existing recommendations in plain language, prioritizing the ones with higher priority.",
    "The `merchants` field lists structured knowledge-graph profiles for every merchant recognized so far — industry, category, tags, recurring-friendliness, and spend — already resolved by a deterministic merchant intelligence engine. Reason about spending using these merchant profiles rather than re-deriving merchant identity from transaction notes yourself.",
    "The `recurring` field lists subscriptions and recurring income/expenses already detected by a deterministic recurring-transaction engine, each with its frequency, average amount, next expected date, and status. Do not try to spot recurring patterns yourself from `recentTransactions` — treat this list as the complete, authoritative set of recurring items, and only explain what they mean (e.g. upcoming renewals, missed payments) in plain language.",
    "The `forecast` field (if present) is a complete cash-flow projection already computed by a deterministic forecasting engine — projected month-end balance, expected income/expenses/savings, a daily safe-spend allowance, a confidence score, and per-category budget risk levels. Do not recalculate any of these numbers or invent your own projection. Instead: explain *why* the forecast looks this way given the other analytics (e.g. which categories are driving risk, whether income is on track), what assumptions the projection is implicitly making (e.g. recent spending pace continues, recurring items land on schedule), and what concrete actions could improve the projected outcome.",
    "The `explanations` field lists structured explanations already generated by a deterministic Financial Insight & Explanation Engine for the budgets, forecast, recommendations, recurring items, and events above — each has its own `reason`, `supportingEvidence`, and `confidence`. This is the authoritative *why* behind those objects: do not derive your own reasoning about them from the raw numbers elsewhere in this payload — draw your `summary`, `watchOutFor`, and `suggestions` from these explanations' reasons and evidence, in plain conversational language.",
    "Your job is only to explain spending patterns and give personalized, actionable financial advice based on the structured analytics below.",
    "",
    "Analytics (JSON):",
    JSON.stringify(analytics),
    "",
    "Respond with ONLY a single JSON object, no markdown, no code fences, no commentary outside the JSON, matching exactly this shape:",
    '{"summary": string, "goodHabits": string[], "watchOutFor": string[], "suggestions": string[]}',
    "- summary: a short, plain-language paragraph explaining the person's overall spending behavior.",
    "- goodHabits: positive patterns worth reinforcing.",
    "- watchOutFor: concerning patterns or risks.",
    "- suggestions: concrete, actionable recommendations.",
  ].join("\n");
}

function stripCodeFence(raw: string): string {
  const trimmed = raw.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  return fenced ? fenced[1] : trimmed;
}

function isStringArray(value: unknown): value is string[] {
  return Array.isArray(value) && value.every((item) => typeof item === "string");
}

function parseCoachResponse(raw: string): CoachOutput {
  const parsed: unknown = JSON.parse(stripCodeFence(raw));
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("Coach response was not a JSON object");
  }
  const { summary, goodHabits, watchOutFor, suggestions } = parsed as Record<
    string,
    unknown
  >;
  if (
    typeof summary !== "string" ||
    !isStringArray(goodHabits) ||
    !isStringArray(watchOutFor) ||
    !isStringArray(suggestions)
  ) {
    throw new Error("Coach response did not match the expected shape");
  }
  return { summary, goodHabits, watchOutFor, suggestions };
}

export async function generateFinancialSummary(
  input: CoachInput,
): Promise<CoachOutput> {
  const analytics = buildAnalyticsPayload(input);
  const prompt = buildPrompt(analytics);
  const raw = await generateText(prompt);
  return parseCoachResponse(raw);
}

function buildQueryPrompt(question: string, intent: QueryIntent, context: QueryContext): string {
  return [
    "You are a financial coach answering a user's direct question about their own finances.",
    "The `context` JSON below was already retrieved and computed by a deterministic Financial Query Engine — it queried the appropriate engines (transactions, budgets, merchants, recurring items, forecast, events, or recommendations) and assembled exactly the data needed to answer this question.",
    "You have NEVER seen the user's raw transaction database and cannot search it. Answer using ONLY the numbers and facts present in `context`. If `context` doesn't contain enough information to answer, say so plainly rather than guessing or inventing figures.",
    `The engine classified this question's intent as "${intent}".`,
    "Do not recalculate, second-guess, or contradict any number in `context` — it is already correct. Your job is only to explain it in clear, natural, conversational language, as a direct answer to the user's question.",
    "`context.explanation`, if present, was already generated by a deterministic Financial Insight & Explanation Engine — it contains the authoritative `reason`, `supportingEvidence`, and `confidence` behind this answer. Draw your explanation of *why* the answer is what it is from there rather than inventing your own reasoning.",
    "All amounts are in Indian Rupees — use the ₹ symbol, never $.",
    "",
    `Question: ${question}`,
    "",
    "Context (JSON):",
    JSON.stringify(context),
    "",
    "Respond with ONLY a single JSON object, no markdown, no code fences, no commentary outside the JSON, matching exactly this shape:",
    '{"answer": string}',
    "- answer: a direct, conversational, plain-language answer to the question — a sentence or two, not a report. Use the actual numbers from context where relevant.",
  ].join("\n");
}

function parseQueryResponse(raw: string): string {
  const parsed: unknown = JSON.parse(stripCodeFence(raw));
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("Query response was not a JSON object");
  }
  const { answer } = parsed as Record<string, unknown>;
  if (typeof answer !== "string") {
    throw new Error("Query response did not match the expected shape");
  }
  return answer;
}

/**
 * The AI Financial Coach's query-answering half: takes the structured
 * context the Query Engine already retrieved and turns it into a
 * conversational answer. The LLM never sees a transaction list it wasn't
 * explicitly handed, and never performs a calculation — every number in
 * its answer must trace back to `context`.
 */
export async function answerFinancialQuery(
  question: string,
  intent: QueryIntent,
  context: QueryContext,
): Promise<string> {
  const prompt = buildQueryPrompt(question, intent, context);
  const raw = await generateText(prompt);
  return parseQueryResponse(raw);
}
