-- Email Intelligence Framework: two brand-new models, since it's a
-- distinct concept from EmailMetadata (a thin document-linkage stub for
-- the Document Intelligence pipeline) and from Connection (Connection
-- Hub's OAuth identity, not this framework's own provider registrations).
-- Import-run history deliberately reuses SyncJob/SyncHistoryEvent
-- (category EMAIL_IMPORT) rather than a third near-duplicate history
-- table. Purely additive — no existing table touched.
--
-- Hand-written and reviewed before applying (not generated by
-- `prisma migrate dev`'s auto-diff), same as the two prior migrations.

-- CreateEnum
CREATE TYPE "EmailProviderConnectionStatus" AS ENUM ('CONNECTED', 'DISCONNECTED', 'AUTHENTICATING', 'ERROR');

-- CreateEnum
CREATE TYPE "EmailIntelligenceType" AS ENUM ('RECEIPT', 'INVOICE', 'SUBSCRIPTION_RENEWAL', 'REFUND', 'SALARY_SLIP', 'UTILITY_BILL', 'CREDIT_CARD_STATEMENT', 'BANK_STATEMENT', 'FLIGHT_BOOKING', 'HOTEL_BOOKING', 'INSURANCE', 'LOAN', 'INVESTMENT_REPORT', 'TAX_DOCUMENT', 'UNKNOWN');

-- CreateEnum
CREATE TYPE "EmailRecordStatus" AS ENUM ('PROCESSED', 'DUPLICATE', 'IMPORTED', 'SKIPPED', 'REJECTED', 'FAILED');

-- CreateTable
CREATE TABLE "email_provider_states" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "lastHealth" JSONB,
    "lastConnection" "EmailProviderConnectionStatus",
    "lastSyncAt" TIMESTAMP(3),
    "installedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "email_provider_states_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "email_records" (
    "id" TEXT NOT NULL,
    "organizationId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "externalId" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "sender" TEXT NOT NULL,
    "receivedAt" TIMESTAMP(3) NOT NULL,
    "emailType" "EmailIntelligenceType" NOT NULL,
    "classificationConfidence" DOUBLE PRECISION NOT NULL,
    "matchedRules" TEXT[],
    "fields" JSONB NOT NULL,
    "validationErrors" JSONB[] DEFAULT ARRAY[]::JSONB[],
    "isDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "duplicateOfId" TEXT,
    "status" "EmailRecordStatus" NOT NULL,
    "linkedTransactionIds" TEXT[],
    "matchedExistingTransactionIds" TEXT[],
    "processedAt" TIMESTAMP(3) NOT NULL,
    "importedAt" TIMESTAMP(3),
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "email_records_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "email_provider_states_organizationId_providerId_key" ON "email_provider_states"("organizationId", "providerId");

-- CreateIndex
CREATE UNIQUE INDEX "email_records_organizationId_providerId_externalId_key" ON "email_records"("organizationId", "providerId", "externalId");

-- CreateIndex
CREATE INDEX "email_records_organizationId_status_idx" ON "email_records"("organizationId", "status");

-- AddForeignKey
ALTER TABLE "email_provider_states" ADD CONSTRAINT "email_provider_states_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "email_records" ADD CONSTRAINT "email_records_organizationId_fkey" FOREIGN KEY ("organizationId") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;
