-- SyncJob gains real support for provider identity and the distinct
-- "kind of run" concept the app's SyncJobType actually represents.
--
-- Background: the original SyncJobType enum (EMAIL_IMPORT/BANK_SYNC/
-- SMS_IMPORT/ACCOUNT_AGGREGATOR/DOCUMENT) represents provider *category*,
-- not the app's actual SyncJobType (initial/incremental/manual/scheduled/
-- resume/retry) — a naming collision. Also, connectionId alone can't
-- identify every provider: bank/SMS/document sync providers are separate
-- plugin registrations with no Connection row today, only email
-- (Gmail-backed) sync jobs have any prospect of a real connectionId, and
-- even that hasn't converged with Connection Hub yet (see the migration
-- plan's Reconciliation Flag on plugins/gmail/). sync_jobs and
-- sync_history_events are both confirmed empty at the time of this
-- migration, so every change below is a plain rename/add — no backfill.
--
-- Hand-written and reviewed before applying (not generated by
-- `prisma migrate dev`'s auto-diff), after that diff previously tried to
-- touch unrelated generated tsvector columns on other tables and failed
-- partway through (see the recommendation_structured_fields migration's
-- own comment for that incident).

-- Rename the existing category enum to what it actually represents, and
-- add the "other" value the app's SyncProviderCategory union already has.
ALTER TYPE "SyncJobType" RENAME TO "SyncProviderCategory";
ALTER TYPE "SyncProviderCategory" ADD VALUE 'OTHER';

-- The app's actual SyncJobType (the *kind* of run), matching
-- lib/sync/types.ts's SYNC_JOB_TYPES exactly.
CREATE TYPE "SyncRunType" AS ENUM ('INITIAL', 'INCREMENTAL', 'MANUAL', 'SCHEDULED', 'RESUME', 'RETRY');

-- lib/sync/types.ts's SYNC_JOB_STATUSES has two states this enum lacked.
ALTER TYPE "SyncJobStatus" ADD VALUE 'PAUSED';
ALTER TYPE "SyncJobStatus" ADD VALUE 'CANCELLED';

-- AlterTable
ALTER TABLE "sync_jobs" RENAME COLUMN "type" TO "providerCategory";
ALTER TABLE "sync_jobs" ADD COLUMN "providerId" TEXT NOT NULL;
ALTER TABLE "sync_jobs" ADD COLUMN "runType" "SyncRunType" NOT NULL;

-- CreateIndex
CREATE INDEX "sync_jobs_organizationId_providerId_idx" ON "sync_jobs"("organizationId", "providerId");
